# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build-prod
  cypress-e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    # https://github.com/cypress-io/cypress-docker-images
    container: cypress/browsers:node14.17.6-chrome100-ff98
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Headless Chrome
        uses: cypress-io/github-action@v4
        timeout-minutes: 10
        with:
          build: npm run build
          start: node server.js
          browser: chrome
          headless: true
